# Generated by Django 3.1.6 on 2021-10-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('availableCash', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
