# Generated by Django 3.1.6 on 2021-10-17 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_auto_20211017_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='registeredTime',
            field=models.TimeField(default=datetime.datetime(2021, 10, 17, 14, 27, 2, 124947)),
        ),
    ]
