# Generated by Django 3.1.6 on 2021-10-17 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0004_auto_20211017_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='executedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 37, 48, 973439, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='transaction',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 37, 48, 973399, tzinfo=utc)),
        ),
    ]
