# Generated by Django 3.1.6 on 2021-10-17 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0011_auto_20211017_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='a2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='executedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 49, 14, 855073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 49, 14, 854982, tzinfo=utc)),
        ),
    ]
