# Generated by Django 3.1.6 on 2021-10-17 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0012_auto_20211017_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='a2',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='executedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 49, 52, 728366, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 49, 52, 728328, tzinfo=utc)),
        ),
    ]
