# Generated by Django 3.1.6 on 2021-10-17 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0013_auto_20211017_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='executedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 51, 33, 406021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 14, 51, 33, 405941, tzinfo=utc)),
        ),
    ]
