# Generated by Django 3.1.6 on 2021-10-17 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0014_auto_20211017_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='executedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 15, 6, 39, 651115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 15, 6, 39, 651057, tzinfo=utc)),
        ),
    ]
